name = "environment_files"
uuid = "bdde8a5e-4200-46b7-b53c-699985a4c7bf"
authors = ["alfaromartino <alfaromartino@gmail.com>"]
version = "0.1.0"

[deps]
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
Chairmarks = "0ca39b1e-fe0b-4e98-acfc-b1656634c4de"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
FLoops = "cc61a311-1640-44b5-9fba-1b764f453329"
FastBenchmark = "5aff02d6-5711-4357-aa22-8dd251b5ff14"
Folds = "41a02a25-b8f0-4f67-bc48-60067656b558"
LazyArrays = "5078a376-72f3-5289-bfd5-ec5146d43c02"
LoopVectorization = "bdcacae8-1622-11e9-2a5c-532679323890"
OhMyThreads = "67456a42-1dca-4109-a031-0a68de7e3ad5"
Pipe = "b98c9c47-44ae-5843-9183-064241ee97a0"
Skipper = "fc65d762-6112-4b1c-b428-ad0792653d81"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"

[compat]
BenchmarkTools = "1.6.3"
Chairmarks = "1.3.1"
Distributions = "0.25.122"
FLoops = "0.2.2"
FastBenchmark = "0.1.0"
Folds = "0.2.10"
LazyArrays = "2.9.4"
LoopVectorization = "0.12.173"
OhMyThreads = "0.8.3"
Pipe = "1.3.0"
Skipper = "0.1.16"
StaticArrays = "1.9.15"
StatsBase = "0.34.9"
